# Generated by Django 4.1.2 on 2022-10-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='service date')),
                ('service', models.CharField(choices=[('B', 'Bathing'), ('C', 'Cleaning'), ('E', 'Errands'), ('G', 'Grocery Shopping'), ('K', 'Cooking'), ('M', 'Companion Care'), ('R', 'Reading'), ('S', 'Supervising'), ('T', 'Toileting')], default='B', max_length=1)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.agencies')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
