# Generated by Django 4.1.2 on 2022-10-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('B', 'Bathing'), ('C', 'Cleaning'), ('E', 'Errands'), ('G', 'Grocery Shopping'), ('K', 'Cooking'), ('M', 'Companion Care'), ('R', 'Reading'), ('S', 'Supervising'), ('T', 'Toileting')], default='B', max_length=1)),
                ('agencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.agencies')),
            ],
        ),
    ]
